---
title: "Examining Motion"
author: "Amelie Devine"
date: "2024-12-07"
output: html_document
---

## get `ballsnap` df ready
```{r, include=FALSE}
games <- fread("../data/games.csv", data.table=FALSE)
plays <- fread("../data/plays.csv", data.table=FALSE)
players <- fread("../data/players.csv", data.table=FALSE)
player_stats <- fread("../data/player_play.csv", data.table=FALSE)

track_season <- data.table()
for(i in seq(1,9)) {
    temp <- fread(paste0("../data/tracking_week_", i, ".csv"))
    track_season <- rbind(temp, track_season)
}

rm(temp, i)
data.frame(track_season)

plays <- plays %>% 
    select(c("gameId", "playId", "quarter", "down", "yardsToGo", "possessionTeam", "defensiveTeam",
             "yardlineSide", "yardlineNumber", "gameClock", "preSnapHomeScore", "preSnapVisitorScore",
             "absoluteYardlineNumber", "offenseFormation", "receiverAlignment", "playClockAtSnap",
             "qbSpike", "qbKneel", "pff_passCoverage", "pff_manZone"))

plays <- plays %>% 
    mutate(gamePlayId = paste0(gameId, playId),
           receiverAlignment = as.numeric(str_replace_all(receiverAlignment, "x", "")),
           receiverAlignment = case_when(
               receiverAlignment %in% c(32, 31, 41, 21, 20, 30, 10, 42) ~ "odd",
               TRUE ~ "even"
           )) %>% 
    left_join(games %>% select(gameId, homeTeamAbbr, visitorTeamAbbr), by = c("gameId")) %>%
    mutate(gameClockSeconds = as.numeric(substr(gameClock, 1, 2)) * 60 + as.numeric(substr(gameClock, 4, 5)),
           preSnapScoreDiff = abs(preSnapHomeScore - preSnapVisitorScore),
           PreSnapWinner = ifelse(preSnapHomeScore > preSnapVisitorScore, homeTeamAbbr, visitorTeamAbbr),
           garbageTime = case_when(
               quarter == 4 & gameClockSeconds <= 240 & preSnapScoreDiff >= 21 ~ TRUE,
               quarter == 4 & gameClockSeconds <= 120 & preSnapScoreDiff >= 14 ~ TRUE,
               TRUE ~ FALSE)) %>% 
    filter(garbageTime == FALSE,
           qbSpike != TRUE,
           qbKneel != 1,
           down %in% c(3,4)) %>% 
    select(-c("garbageTime")) %>% 
    mutate(offenseScore = case_when(
              possessionTeam == homeTeamAbbr ~ preSnapHomeScore,
              possessionTeam == visitorTeamAbbr ~ preSnapVisitorScore,
              TRUE ~ NA_real_),
           defenseScore = case_when(
              possessionTeam == homeTeamAbbr ~ preSnapVisitorScore,
              possessionTeam == visitorTeamAbbr ~ preSnapHomeScore,
              TRUE ~ NA_real_),
           offenseAhead = case_when(
              offenseScore > defenseScore ~ TRUE,
              TRUE ~ FALSE),
           tieGame = case_when(
              offenseScore == defenseScore ~ TRUE,
              TRUE ~ FALSE)
           ) %>% 
    select(-c("offenseScore", "defenseScore", "PreSnapWinner", "pff_passCoverage", "qbKneel", "qbSpike", 
              "homeTeamAbbr", "visitorTeamAbbr")) %>% 
    mutate(territoryOffense = case_when(
             possessionTeam == yardlineSide ~ TRUE,
             TRUE ~ FALSE)) %>% 
    filter(pff_manZone == "Man" | pff_manZone == "Zone")

player_stats <- player_stats %>% 
    select(c("gameId", "playId", "nflId", "teamAbbr", "inMotionAtBallSnap", 
             "shiftSinceLineset", "motionSinceLineset")) %>% 
    mutate(gamePlayId = paste0(gameId, playId))

players <- players %>% 
    mutate(position_group = case_when(
            position %in% c("ILB", "OLB", "MLB", "LB") ~ "LB", 
            position %in% c("DT", "DE", "NT") ~ "DL",
            position %in% c("SS", "FS", "DB") ~ "S",
            position %in% c("CB") ~ "CB", 
            position %in% c("G", "C", "T") ~ "OL",
            position %in% c("RB", "FB") ~ "RB",
            position %in% c("WR") ~ "WR",
            position %in% c("TE") ~ "TE",
            TRUE ~ "QB")) %>% 
    select(nflId, position, position_group)

player_stats <- player_stats %>%
    filter(gamePlayId %in% plays$gamePlayId) %>%
    left_join(players, by=c("nflId"))   
 
rm(players)

track_season <- track_season %>% 
    mutate(gamePlayId = paste0(gameId, playId)) %>% 
    filter(gamePlayId %in% plays$gamePlayId)

ball_position <- track_season %>% 
    filter(is.na(nflId)) %>% 
    select(gameId, playId, frameId, x, y) %>% 
    rename(ball_x = x, ball_y = y)

track_season <- track_season %>% 
    filter(!is.na(nflId),
           frameType != "AFTER_SNAP") 

ballsnap <- track_season %>% 
    filter(event == "ball_snap") %>%
    select(-c("displayName", "frameType", "jerseyNumber"))

ballsnap <- ballsnap %>% 
    left_join(player_stats, by = c("gameId", "playId", "nflId")) %>% 
    left_join(plays, by = c("gameId", "playId")) %>% 
    left_join(ball_position, by = c("gameId", "playId", "frameId")) %>% 
    select(-c("gamePlayId.x", "gamePlayId.y", "frameId"))
```


## Check Off Motion Variables
```{r}
offensive_actions_summary <- ballsnap  %>%
    filter(position_group %in% c("QB", "OL", "RB", "WR", "TE")) %>% 
    group_by(gameId, playId) %>%
    summarize(any_inMotionAtBallSnap = any(inMotionAtBallSnap == TRUE, na.rm = TRUE),
              count_inMotionAtBallSnap = sum(inMotionAtBallSnap == TRUE, na.rm = TRUE), 
              any_shiftSinceLineset = any(shiftSinceLineset == TRUE, na.rm = TRUE), 
              count_shiftSinceLineset = sum(shiftSinceLineset == TRUE, na.rm = TRUE),
              any_motionSinceLineset = any(motionSinceLineset == TRUE, na.rm = TRUE),
              count_motionSinceLineset = sum(motionSinceLineset == TRUE, na.rm = TRUE), 
              .groups = "drop"
              )

defensive_tracking_data <- ballsnap %>%
    filter(position_group %in% c("DL", "LB", "S", "CB")) %>% 
    left_join(offensive_actions_summary, by = c("gameId", "playId")) 
```

## Off players who move
```{r}
off_motion <- ballsnap %>% 
    filter(position_group %in% c("QB", "OL", "RB", "WR", "TE")) %>% 
    filter(inMotionAtBallSnap == TRUE | shiftSinceLineset == TRUE | motionSinceLineset == TRUE) %>% 
    select(gameId, playId, gamePlayId, nflId, frameId, x, y) %>%
    rename(offense_x = x, offense_y = y)

defensive_movements <- ballsnap %>%
    filter(position_group %in% c("DL", "LB", "S", "CB")) %>%
    select(gameId, playId, nflId, frameId, x, y)

responses <- off_motion %>%
    left_join(defensive_movements, by = c("gameId", "playId", "frameId")) %>%
    mutate(distance = sqrt((offense_x - x)^2 + (offense_y - y)^2) ) %>%
    group_by(gameId, playId, nflId.x) %>% 
    summarise(closest_defender_start = nflId.y[which.min(distance)], .groups = "drop")

debug_data <- off_motion %>%
    left_join(defensive_movements, by = c("gameId", "playId", "frameId"))

head(debug_data) ### how can i tell which player is in motion?? look at that!
```

## viz check
```{r}
set.seed(128)

play_to_plot <- off_motion %>% 
    pull(gamePlayId) %>% 
    sample(1) 

plot_data <- track_sample %>%
    filter(gamePlayId == play_to_plot)
    
ggplot(plot_data, aes(x = x, y = y, color = side_of_ball)) +
    geom_point() +
    geom_path(aes(group = nflId), alpha = 0.5) + 
    labs(title = paste("Defensive Response to Offensive Shift: Play", play_to_plot),
         x = "X Position", y = "Y Position") +
    theme_minimal()
```
